name: cc
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://conda.anaconda.org/pytorch
  - defaults
dependencies:
  - matplotlib==3.10.6=py310haa95532_1
  - prompt-toolkit==3.0.52=py310haa95532_1
  - matplotlib-base==3.10.6=py310h43afe63_1
  - nest-asyncio==1.6.0=py310haa95532_0
  - libwebp-base==1.3.2=h3d04722_1
  - libzlib==1.3.1=h02ab6af_0
  - wheel==0.45.1=py310haa95532_0
  - comm==0.2.3=py310haa95532_0
  - pure_eval==0.2.3=py310haa95532_0
  - markupsafe==3.0.2=py310h827c3e9_0
  - fontconfig==2.15.0=hd211d86_0
  - ipython==8.30.0=py310haa95532_0
  - mysql-common==9.3.0=hf582a5b_3
  - typing-extensions==4.15.0=py310haa95532_0
  - jupyter_core==5.8.1=py310haa95532_0
  - pyyaml==6.0.2=py310h827c3e9_0
  - decorator==5.2.1=py310haa95532_0
  - wcwidth==0.2.13=py310haa95532_0
  - cairo==1.18.4=he9e932c_0
  - tornado==6.5.1=py310h827c3e9_0
  - tzdata==2025b=h04d1e81_0
  - typing_extensions==4.15.0=py310haa95532_0
  - nbconvert-core==7.16.6=py310haa95532_0
  - pillow==11.1.0=py310h096bfcc_0
  - jupyterlab_server==2.28.0=py310haa95532_0
  - vc14_runtime==14.44.35208=h4927774_10
  - pyparsing==3.2.0=py310haa95532_0
  - pyqt6-sip==13.10.2=py310h630b2a1_0
  - psutil==7.0.0=py310h02ab6af_1
  - jupyterlab==4.4.7=py310haa95532_0
  - mistune==3.1.2=py310haa95532_0
  - matplotlib-inline==0.2.1=py310haa95532_0
  - qtwebsockets==6.9.2=heb02b0b_1
  - libiconv==1.16=h2bbff1b_3
  - blas==1.0=mkl
  - jupyter_events==0.12.0=py310haa95532_0
  - jsonschema==4.25.0=py310haa95532_1
  - tbb==2022.0.0=h214f63a_0
  - lerc==3.0=hd77b12b_0
  - six==1.17.0=py310haa95532_0
  - xz==5.6.4=h4754444_1
  - mysql-libs==9.3.0=hc0ebf12_3
  - tk==8.6.15=hf199647_0
  - sqlite==3.51.0=hda9a48d_0
  - platformdirs==4.5.0=py310haa95532_0
  - prompt_toolkit==3.0.52=hd3eb1b0_1
  - h11==0.16.0=py310haa95532_1
  - openssl==3.0.18=h543e019_0
  - qtwebchannel==6.9.2=heb02b0b_1
  - pcre2==10.46=h5740b90_0
  - requests==2.32.5=py310haa95532_1
  - certifi==2025.11.12=py310haa95532_0
  - beautifulsoup4==4.13.5=py310haa95532_0
  - colorama==0.4.6=py310haa95532_0
  - vc==14.3=h2df5915_10
  - zeromq==4.3.5=h6c54ac7_1
  - harfbuzz==10.2.0=he2f9f60_1
  - pyzmq==27.1.0=py310h7149c55_1
  - rpds-py==0.28.0=py310h114bc41_0
  - executing==2.2.1=py310haa95532_0
  - pixman==0.46.4=h4043f72_0
  - brotlicffi==1.1.0.0=py310h885b0b7_0
  - graphite2==1.3.14=hd77b12b_1
  - libpng==1.6.50=h46444df_0
  - jupyter_console==6.6.3=py310haa95532_0
  - qtsvg==6.9.2=h30ace32_1
  - lz4-c==1.9.4=h2bbff1b_1
  - freetype==2.13.3=h0620614_0
  - rfc3986-validator==0.1.1=py310haa95532_0
  - cycler==0.11.0=pyhd3eb1b0_0
  - expat==2.7.3=h9214b88_0
  - jupyter==1.1.1=py310haa95532_0
  - ucrt==10.0.22621.0=haa95532_0
  - libsodium==1.0.20=h83e8143_0
  - winpty==0.4.3=4
  - bottleneck==1.4.2=py310h540bb41_1
  - notebook-shim==0.2.4=py310haa95532_0
  - rfc3339-validator==0.1.4=py310haa95532_0
  - pandas==2.3.3=py310h42c1672_1
  - argon2-cffi==21.3.0=pyhd3eb1b0_0
  - libkrb5==1.21.3=h885b0b7_4
  - urllib3==2.5.0=py310haa95532_0
  - contourpy==1.3.1=py310h214f63a_0
  - anyio==4.10.0=py310haa95532_0
  - kiwisolver==1.4.8=py310h5da7b33_0
  - nbclient==0.10.2=py310haa95532_0
  - ipywidgets==8.1.7=py310haa95532_0
  - attrs==25.4.0=py310haa95532_2
  - sip==6.12.0=py310h706e071_0
  - pip==25.3=pyhc872135_0
  - pandocfilters==1.5.1=py310haa95532_0
  - jupyterlab_widgets==3.0.15=py310haa95532_0
  - jupyter-lsp==2.2.5=py310haa95532_0
  - debugpy==1.8.16=py310h885b0b7_1
  - jupyterlab_pygments==0.3.0=py310haa95532_0
  - qtconsole==5.7.0=py310haa95532_0
  - widgetsnbextension==4.0.14=py310haa95532_0
  - prometheus_client==0.21.1=py310haa95532_0
  - tbb-devel==2022.0.0=h214f63a_0
  - qttools==6.9.2=h7e7b719_1
  - fonttools==4.60.1=py310h02ab6af_0
  - jedi==0.19.2=py310haa95532_0
  - exceptiongroup==1.3.0=py310haa95532_0
  - mkl==2025.0.0=h5da7b33_930
  - idna==3.11=py310haa95532_0
  - terminado==0.18.1=py310haa95532_0
  - ipython_pygments_lexers==1.1.1=py310haa95532_0
  - json5==0.9.25=py310haa95532_0
  - openjpeg==2.5.2=hae555c5_0
  - python-fastjsonschema==2.20.0=py310haa95532_0
  - qtdeclarative==6.9.2=h88b4c33_1
  - parso==0.8.5=py310haa95532_0
  - jinja2==3.1.6=py310haa95532_0
  - libglib==2.84.4=hfaec014_0
  - intel-openmp==2025.0.0=haa95532_1164
  - pytz==2025.2=py310haa95532_0
  - setuptools==80.9.0=py310haa95532_0
  - pygments==2.19.2=py310haa95532_0
  - soupsieve==2.5=py310haa95532_0
  - tinycss2==1.4.0=py310haa95532_0
  - ipykernel==6.31.0=py310h4442805_0
  - zlib==1.3.1=h02ab6af_0
  - babel==2.16.0=py310haa95532_0
  - libffi==3.4.4=hd77b12b_1
  - traitlets==5.14.3=py310haa95532_0
  - win_inet_pton==1.1.0=py310haa95532_1
  - bleach==6.2.0=py310haa95532_0
  - qtpy==2.4.3=py310haa95532_0
  - webencodings==0.5.1=py310haa95532_1
  - zstd==1.5.7=h56299aa_0
  - jsonschema-specifications==2025.9.1=py310haa95532_0
  - bzip2==1.0.8=h2bbff1b_6
  - cffi==2.0.0=py310h02ab6af_1
  - pandoc==3.8=haa95532_0
  - libdeflate==1.17=h2bbff1b_1
  - async-lru==2.0.5=py310haa95532_0
  - mkl_fft==2.1.1=py310h300f80d_0
  - python-dateutil==2.9.0post0=py310haa95532_2
  - mkl-service==2.5.2=py310h0b37514_0
  - python-tzdata==2025.2=pyhd3eb1b0_0
  - nbformat==5.10.4=py310haa95532_0
  - stack_data==0.6.3=py310haa95532_0
  - numexpr==2.14.1=py310h7660c64_0
  - qtbase==6.9.2=hd965823_2
  - libpq==17.6=h652a1e2_0
  - httpx==0.28.1=py310haa95532_1
  - notebook==7.4.5=py310haa95532_0
  - pysocks==1.7.1=py310haa95532_1
  - pywinpty==2.0.15=py310h72d21ff_0
  - send2trash==1.8.2=py310haa95532_1
  - websocket-client==1.8.0=py310haa95532_0
  - nbconvert==7.16.6=py310haa95532_0
  - mkl_random==1.3.0=py310ha5e6156_0
  - tomli==2.2.1=py310haa95532_0
  - libxml2==2.13.9=h6201b9f_0
  - sniffio==1.3.0=py310haa95532_0
  - referencing==0.37.0=py310haa95532_0
  - vs2015_runtime==14.44.35208=ha6b5a95_10
  - packaging==25.0=py310haa95532_1
  - jupyter_client==8.6.3=py310haa95532_1
  - httpcore==1.0.9=py310haa95532_0
  - lcms2==2.16=hb4a4139_0
  - overrides==7.7.0=py310haa95532_0
  - icu==73.1=h6c2663c_0
  - libtiff==4.5.1=hd77b12b_0
  - jpeg==9f=ha349fce_0
  - defusedxml==0.7.1=pyhd3eb1b0_0
  - yaml==0.2.5=he774522_0
  - jupyter_server==2.16.0=py310haa95532_0
  - nbconvert-pandoc==7.16.6=py310haa95532_0
  - asttokens==3.0.0=py310haa95532_0
  - argon2-cffi-bindings==25.1.0=py310h02ab6af_0
  - charset-normalizer==3.4.4=py310haa95532_0
  - pycparser==2.23=py310haa95532_0
  - python-json-logger==3.2.1=py310haa95532_0
  - ca-certificates==2025.11.4=haa95532_0
  - pywin32==311=py310h885b0b7_0
  - python==3.10.19=h981015d_0
  - pyqt==6.9.1=py310h12ec796_0
  - jupyter_server_terminals==0.5.3=py310haa95532_0
prefix: D:\ann\envs\cc
